# kubectl create secret generic sample-app --from-literal=MYSQL_PASSWORD=password --dry-run=client -o yaml > sample-app-secret.yaml
apiVersion: v1
data:
  MYSQL_PASSWORD: cGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: null
  name: sample-app
