# kubectl create configmap sample-app --from-env-file=env.txt --dry-run=client -o yaml > sample-app-configmap.yaml
apiVersion: v1
data:
  MYSQL_DATABASE: "test_db"
  MYSQL_HOST: "mysql.database.svc.cluster.local"
  MYSQL_USER: "sample_app"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sample-app
