apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data: # base64
  data.csv: bmFtZSxhZ2UsZW1haWwscGFzc3dvcmQKICAgIHVlbm8sMSx1ZW5vQGV4YW1wbGUuY29tLGpkc2ZxZTE4MwogICAgdG9tb3lhLDIsdG9tb3lhQGV4YW1wbGUuY29tLGtsMmVyZjM0
# 複数のオブジェクトを定義する
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox:1.30
      command:
        - "sleep"
        - "3600"
      volumeMounts:
        - mountPath: "/datadir"
          name: secret
          readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: mysecret