apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  username: YWRtaW4= # admin
  password: cGFzc3dvcmQ= # password

# 複数のオブジェクトを定義する
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox:1.30
      command:
        - "env"
      envFrom:
        - secretRef:
            name: mysecret