apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  TEST_ENV: "test"

# 複数のオブジェクトを定義する
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox:1.30
      command:
        - "env"
      envFrom:
        - configMapRef:
            name: test-config
